### ISSUE TITLE
Interaction design clean-up for adding new dataset 

### ISSUE THREAD

**Issue by kanitw** [uwdata/voyager#145]
The button shouldn’t be like this.  (Maybe just put plus on the right?)

![data_voyager](https://cloud.githubusercontent.com/assets/111269/7168471/8dfd6730-e372-11e4-8ea4-5a985a7dda5c.png)

**Comment by jheer** [comment]
Or, make "Add Dataset" an option _in_ the dropdown that, when selected,
causes an appropriate dialog to pop up?

**Comment by domoritz** [comment]
Other things to do:
* [ ] separate default datasets and datasets added by the user
* [ ] store metadata for added datasets in local storage

**Comment by domoritz** [comment]
Lyra has the "add dataset" in the dropdown. Let's do that as well.

**Comment by domoritz** [comment]
I will make this a modal at some point but it's better now so closing for now.

**Comment by domoritz** [comment]
Oh, and move it over to vl-ui and thus voyager. It's on my agenda.

**Comment by kanitw** [comment]
Cool.  I think it's duplicate with https://github.com/uwdata/vega-lite-ui/issues/3
