### ISSUE TITLE
Create Editable Description on "i button" Information Hover

### ISSUE THREAD

**Issue by Marviel** [uwdata/voyager#177]
Not mission-critical, but...

Would be cool to be allowed to type some "description" text for each field, to be displayed when the "i button" is hovered over, in addition to the other information that is displayed.

**Comment by domoritz** [comment]
That should be easy to add to the schema. Contributions are welcome.

FYI, this is a https://github.com/uwdata/vega-lite-ui issue.

**Comment by domoritz** [comment]
Moved to https://github.com/uwdata/vega-lite-ui/issues/60
